all:
  vars:
    ansible_user: root
  children:
    freeipa_managed:
      children:
        mail_servers:
          hosts:
            mail.massopen.cloud:
        auth_servers:
          hosts:
            sso1.massopen.cloud:
            sso2.massopen.cloud:
        hil_servers:
          hosts:
            kumo-hil-client.infra.massopen.cloud:
